{"name": "Логин с неверными учетными данными", "status": "passed", "parameters": [{"name": "test_cases_input", "value": "{'email': 'wrong@example', 'password': 'wrongpassword'}"}], "start": 1741824935787, "stop": 1741824935895, "uuid": "eaba7627-a185-49f7-841c-bdcbd4e1fdce", "historyId": "dfa3a5c7bc8f2d6c259614b85a7806c3", "testCaseId": "cf44ea55174a74afa9efcb95a068cfd0", "fullName": "tests.test_login_user.TestLogin#test_login_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TerekhovHONOR"}, {"name": "thread", "value": "18088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}