{"name": "Логин с неверными учетными данными", "status": "passed", "parameters": [{"name": "test_cases_input", "value": "{'email': '', 'password': 'password'}"}], "start": 1741824936006, "stop": 1741824936180, "uuid": "0b091f5d-12cc-49c0-833c-b7a7daa29cda", "historyId": "f7f97921abbb572c58b426c682db85c1", "testCaseId": "cf44ea55174a74afa9efcb95a068cfd0", "fullName": "tests.test_login_user.TestLogin#test_login_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TerekhovHONOR"}, {"name": "thread", "value": "18088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}