{"name": "Логин с неверными учетными данными", "status": "passed", "parameters": [{"name": "test_cases_input", "value": "{'email': '', 'password': ''}"}], "start": 1741824936306, "stop": 1741824936418, "uuid": "7026fa24-63f3-44b8-afd4-4c05c95f452a", "historyId": "ed2b62ad245ac23b6474f8cb08606d19", "testCaseId": "cf44ea55174a74afa9efcb95a068cfd0", "fullName": "tests.test_login_user.TestLogin#test_login_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TerekhovHONOR"}, {"name": "thread", "value": "18088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}